# Generated by Django 4.0.5 on 2022-06-18 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=3)),
                ('ingredients', models.TextField(max_length=500)),
                ('recipe', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='')),
                ('outside_notes', models.CharField(blank=True, max_length=400, null=True)),
                ('final_notes', models.CharField(blank=True, max_length=400, null=True)),
                ('adjustments', models.CharField(blank=True, max_length=455, null=True)),
                ('feedback_link', models.URLField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('variation_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('successful_variation', models.BooleanField(default=False)),
                ('chef', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.recipe')),
            ],
        ),
    ]
