# Generated by Django 4.0.5 on 2022-06-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_note_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_tag',
        ),
        migrations.RemoveField(
            model_name='recipeversion',
            name='recipe_note',
        ),
        migrations.RemoveField(
            model_name='recipeversion',
            name='recipe_note_tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='note_tag',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to='api.note'),
        ),
        migrations.AddField(
            model_name='tag',
            name='recipe_version_tag',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_version_tags', to='api.recipeversion'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
