# Generated by Django 4.0.5 on 2022-06-22 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_note_note_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
