# Generated by Django 4.0.5 on 2022-06-22 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_note_note_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasterfeedback',
            name='test_version_number',
        ),
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='note_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='recipe_version',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.recipeversion'),
        ),
        migrations.AlterField(
            model_name='recipeversion',
            name='chef',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='note_tag',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.note'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='recipe_version_tag',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.recipeversion'),
        ),
        migrations.AlterField(
            model_name='tasterfeedback',
            name='test_recipe',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='taster_feedbacks', to='api.recipeversion'),
        ),
    ]
