# Generated by Django 4.0.5 on 2022-06-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_tasterfeedback_test_version_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='note_tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='note_tag',
            field=models.ManyToManyField(related_name='tags', to='api.note'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='recipe_version_tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='recipe_version_tag',
            field=models.ManyToManyField(related_name='tags', to='api.recipeversion'),
        ),
        migrations.AlterField(
            model_name='tasterfeedback',
            name='tester',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='taster_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
