# Generated by Django 4.0.5 on 2022-06-25 21:17

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('api', '0013_remove_tag_note_tag_tag_note_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeversion',
            options={'verbose_name': 'RecipeVersion', 'verbose_name_plural': 'RecipeVersions'},
        ),
        migrations.AlterModelOptions(
            name='tasterfeedback',
            options={'verbose_name': 'TasterFeedback', 'verbose_name_plural': 'TasterFeedbacks'},
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='tasterfeedback',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='note',
            name='recipe_version',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.recipeversion'),
        ),
        migrations.AlterField(
            model_name='recipeversion',
            name='version_number',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
