# Generated by Django 4.0.5 on 2022-06-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_recipeversion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeversion',
            name='version_number',
            field=models.CharField(max_length=3),
        ),
    ]
