# Generated by Django 4.0.5 on 2022-06-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_recipeversion_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='recipe_version',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.recipeversion'),
        ),
    ]
