# Generated by Django 4.0.5 on 2022-06-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_note_note_alter_note_recipe_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tasterfeedback',
            name='tags',
        ),
        migrations.AlterField(
            model_name='tasterfeedback',
            name='portion',
            field=models.CharField(choices=[('----------', '----------'), ('Too Little', 'Too Little'), ('Just Right', 'Just Right'), ('Too Much', 'Too Much')], default='----------', max_length=11),
        ),
        migrations.AlterField(
            model_name='tasterfeedback',
            name='rating',
            field=models.CharField(choices=[('-', '-'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='-', max_length=6),
        ),
        migrations.AlterField(
            model_name='tasterfeedback',
            name='saltiness',
            field=models.CharField(choices=[('----------', '----------'), ('Too Little', 'Too Little'), ('Just Right', 'Just Right'), ('Too Much', 'Too Much')], default='----------', max_length=11),
        ),
        migrations.AlterField(
            model_name='tasterfeedback',
            name='sweetness',
            field=models.CharField(choices=[('----------', '----------'), ('Too Little', 'Too Little'), ('Just Right', 'Just Right'), ('Too Much', 'Too Much')], default='----------', max_length=11),
        ),
        migrations.AlterField(
            model_name='tasterfeedback',
            name='texture',
            field=models.CharField(choices=[('---', '---'), ('Yes', 'Yes'), ('No', 'No')], default='---', max_length=5),
        ),
    ]
