# Generated by Django 4.0.5 on 2022-06-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeversion',
            name='tags',
        ),
    ]
