# Generated by Django 4.0.5 on 2022-06-27 10:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('api', '0019_remove_recipeversion_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeversion',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
