# Generated by Django 4.0.5 on 2022-06-30 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_note_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasterfeedback',
            name='tester',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taster_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
