# Generated by Django 4.0.5 on 2022-07-01 15:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_tasterfeedback_additional_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeversion',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='recipeversion',
            name='recipe_steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
